### ISSUE TITLE
Ya gotta push, boy!

### ISSUE THREAD

**Issue by chtzvt** [AzuraDev/CameraLWJGL#1]
Commit, then push to master!

**Comment by AzuraDev** [comment]
Lol i never use github im looking around

**Comment by chtzvt** [comment]
Ah, I see. But if you want to put things in your repo, add, commit, and
push.

"Shrek est ama, Shrek est vita." -Ancient Roman Proverb

**Comment by AzuraDev** [comment]
thnx :D
